image: python:3.12-slim

stages:
  - build
  - deploy

variables:
  BUILD_VERSION: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID

dockerize_project:
  stage: build
  only:
    - demo
    - test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: $REGISTRY_URL_TEST/$CI_PROJECT_ROOT_NAMESPACE/$CI_PROJECT_NAME
  script:
    - "docker build -t $(echo $DOCKER_IMAGE | tr '[:upper:]' '[:lower:]'):latest ."
    - "docker push $(echo $DOCKER_IMAGE | tr '[:upper:]' '[:lower:]'):latest"
    - "docker build -t $(echo $DOCKER_IMAGE | tr '[:upper:]' '[:lower:]'):$BUILD_VERSION ."
    - "docker push $(echo $DOCKER_IMAGE | tr '[:upper:]' '[:lower:]'):$BUILD_VERSION"
  tags: [shell-test]

deploy-test:
  stage: deploy
  only:
    refs: 
      - test
  except:
    - tags
  environment:
    name: test
    url: http://${CI_ENVIRONMENT_SLUG}.ehealth.kz
  script:
    - git clone https://gitlab-ci-token:$CI_JOB_TOKEN@$GITLAB_ADDR/${CI_PROJECT_NAMESPACE}/deploy.git
    - sh deploy/deploy.sh
  tags: [test]

