variables:
  BUILD_VERSION: $CI_COMMIT_REF_NAME-$CI_PIPELINE_ID

stages:
  - deploy-test
  - release
  - containerize-prod
  - deploy-prod

include:
  - project: 'devops/ci-cd'
    ref: main
    file: 'containerize/docker-frontend.yml'

  - project: 'devops/ci-cd'
    ref: main
    file: 'release/release.yml'

  - project: 'devops/ci-cd'
    ref: main
    file: 'deploy/deploy-frontend.yml'

